spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: false
    sharding:
      default-data-source-name: master
    masterslave:
      # 读写分离配置
      #配置slave节点的负载均衡均衡策略,采用轮询机制
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: ms
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave1,slave2
      props:
        sql:
          show: true #开启SQL显示，默认false
    datasource:
      names: master,slave1,slave2
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://59.110.66.69:3306/electronicdictionary?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 120120
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://59.110.66.69:3307/electronicdictionary?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 120120
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://59.110.66.69:3308/electronicdictionary?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 120120
  thymeleaf:
    cache: false
  datasource:
    #    username: root
    #    password: 120120
    #    url: jdbc:mysql://59.110.66.69:3306/electronicdictionary?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 主库数据源
#      master:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://59.110.66.69:3306/electronicdictionary?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
#        username: root
#        password: 120120
#      # 从库数据源
#      slave:
#        # 从数据源开关/默认关闭
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        enabled: true
#        url: jdbc:mysql://59.110.66.69:3307/electronicdictionary?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
#        username: root
#        password: 120120

      stat-view-servlet:
        enabled: true
        login-username: syc
        login-password: 120120
      web-stat-filter:
        enabled: true
        url-pattern: /*
        session-stat-enable: true
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filters: stat,wall,session
      aop-patterns: com.shi.electronicdictionary.*



  resources:
    add-mappings: true

#mybatis_plus?useUnicode=true
#Hongkong
mybatis:
  type-aliases-package: com/shi/electronicdictionary/pojo # 实体类所在的位置
  mapper-locations: classpath:mapper/*.xml # mapper映射文件位置
  configuration:
    map-underscore-to-camel-case: true
    #call-setters-on-nulls: true #设置返回字段不为空，前端不报错
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql