spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 120120
    url: jdbc:mysql://localhost:3306/electronicdictionary?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
#    type: com.zaxxer.hikari.HikariDataSource
    druid:
      stat-view-servlet:
        enabled: true
        login-username: syc
        login-password: 120120
      web-stat-filter:
        enabled: true
        url-pattern: /*
        session-stat-enable: true
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filters: stat,wall,session
      aop-patterns: com.shi.electronicdictionary.*
    type: com.alibaba.druid.pool.DruidDataSource


  resources:
    add-mappings: true

#mybatis_plus?useUnicode=true
#Hongkong
mybatis:
  type-aliases-package: com/shi/electronicdictionary/pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
